use_default_settings: true

search:
  safe_search: 0
  default_lang: "de"
  formats:
    - html
    - json

server:
  secret_key: "ein-sehr-sicherer-schluessel-12345" 
  limiter: false
  image_proxy: false
